#!/bin/bash
function check_installed() {
	if ! command -v $1 &>/dev/null; then
		echo "$1 could not be found"
		exit 1
	fi
}
function confirm() {
	printf "%s [Y/n]\n" "$1"
	read -n 1 -r
	echo
	if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
		exit 1
	fi
}
check_installed mksquashfs

ROOT="$PWD/root"
confirm "The installation directory is $ROOT. Continue?"
mkdir root
