#!/bin/sh
set -o errexit
KERNEL="$(pacman -Q linux | awk '{print $2}' | sed 's/\.\([a-z]\+\)/-\1/')"
echo "Generating initramfs for kernel $KERNEL"
echo "This may take a while..."
echo "Generaing /boot/initramfs-linux.img..."
dracut -N /boot/initramfs-linux.img -f "$KERNEL"
cp -fv -- /boot/initramfs-linux.img /boot/initramfs-linux-fallback.img
